# Generated by Django 4.1.3 on 2023-05-24 16:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Delete_account_Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_reason', models.CharField(blank=True, choices=[("I don't understand how to use Travaii", "I don't understand how to use Travaii"), ("I don't find Travaii useful", "I don't find Travaii useful"), ("I'm getting too many spam calls and emails", "I'm getting too many spam calls and emails"), ('I have privacy concerns', 'I have privacy concerns')], max_length=300, null=True)),
                ('reason_txt', models.TextField()),
                ('email_user', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='desired_Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_field', models.EmailField(max_length=254)),
                ('job_category', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to='')),
                ('linkedin', models.URLField(blank=True, null=True, unique=True)),
                ('github', models.URLField(blank=True, null=True, unique=True)),
                ('p_website', models.URLField(blank=True, null=True, unique=True)),
                ('applicant_cv', models.FileField(blank=True, upload_to='resume/applicant/%y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'docx'])])),
                ('birthday', models.DateField()),
                ('about', models.TextField(blank=True, null=True)),
                ('is_public', models.CharField(choices=[('Anyone', 'Anyone'), ('Only you', 'Only you')], default='Anyone', max_length=20)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('submited', models.BooleanField(default=False)),
                ('submition_date', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicant_city', to='applicants.cities')),
            ],
        ),
    ]
