# Generated by Django 4.1.3 on 2022-12-11 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='desired_Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to='')),
                ('linkedin', models.URLField(blank=True, null=True, unique=True)),
                ('github', models.URLField(blank=True, null=True, unique=True)),
                ('p_website', models.URLField(blank=True, null=True, unique=True)),
                ('applicant_cv', models.FileField(blank=True, upload_to='resume/applicant/%y/%m/%d')),
                ('birthday', models.DateField()),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('is_public', models.CharField(choices=[('Anyone', 'Anyone'), ('Only you', 'Only you')], default='Anyone', max_length=20)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('submited', models.BooleanField(default=False)),
                ('submition_date', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_city', to='applicants.cities')),
            ],
        ),
    ]
