# Generated by Django 4.1.3 on 2023-05-24 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('applicants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='desired_industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicant_job_industry', to='main.category'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='desired_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicant_job', to='applicants.desired_position'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='desired_job_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicant_job_type', to='main.job_type'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='desired_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicant_job_shift', to='main.shifts'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='languages',
            field=models.ManyToManyField(blank=True, to='main.languages'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='save_applicant',
            field=models.ManyToManyField(blank=True, related_name='save_applicant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicant_wilaya', to='applicants.wilaya'),
        ),
    ]
