# Generated by Django 4.1.3 on 2023-05-24 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
