# Generated by Django 4.1.3 on 2022-12-13 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='applicant_cv',
            field=models.FileField(blank=True, upload_to='resume/applicant/%y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg'])]),
        ),
    ]
