# Generated by Django 4.1.3 on 2022-12-14 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0003_alter_applicantprofile_applicant_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantprofile',
            name='phone',
        ),
    ]
