# Generated by Django 4.1.3 on 2022-12-27 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0003_alter_applicantprofile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicant_city', to='applicants.cities'),
        ),
    ]
