# Generated by Django 4.1.3 on 2022-12-14 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0004_remove_applicantprofile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delete_account_Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_reason', models.CharField(blank=True, choices=[("I don't understand how to use Travaii", "I don't understand how to use Travaii"), ("I don't find Travaii useful", "I don't find Travaii useful"), ("I'm getting too many spam calls and emails", "I'm getting too many spam calls and emails"), ('I have privacy concerns', 'I have privacy concerns')], max_length=300, null=True)),
                ('reason', models.TextField()),
                ('email_user', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
