# Generated by Django 4.1.3 on 2022-12-14 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0005_delete_account_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delete_account_feedback',
            old_name='reason',
            new_name='reason_txt',
        ),
    ]
