# Generated by Django 4.1.3 on 2023-01-21 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_jobs_description'),
        ('applicants', '0006_alter_applicantprofile_applicant_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='desired_industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicant_job_industry', to='main.category'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='desired_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicant_job', to='applicants.desired_position'),
        ),
    ]
