# Generated by Django 4.1.3 on 2022-12-20 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_privacy_policy'),
        ('applicants', '0007_alter_applicantprofile_applicant_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applicant_city', to='applicants.cities'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='desired_industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applicant_job_industry', to='main.category'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='desired_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applicant_job', to='applicants.desired_position'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='desired_job_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applicant_job_type', to='main.job_type'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='desired_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applicant_job_shift', to='main.shifts'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applicant_wilaya', to='applicants.wilaya'),
        ),
    ]
