# Generated by Django 4.1.3 on 2023-01-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0007_alter_applicantprofile_desired_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='job_category',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
