# Generated by Django 4.1.3 on 2022-12-20 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0008_alter_applicantprofile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicant_wilaya', to='applicants.wilaya'),
        ),
    ]
