# Generated by Django 4.1.3 on 2022-12-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0010_alter_applicantprofile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wilaya',
            name='city_name',
            field=models.TextField(),
        ),
    ]
