# Generated by Django 4.1.3 on 2022-12-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0011_alter_wilaya_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wilaya',
            name='city_name',
            field=models.CharField(max_length=300),
        ),
    ]
