# Generated by Django 4.2.7 on 2023-11-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applying',
            name='experience',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobs',
            name='pay_per',
            field=models.CharField(blank=True, choices=[('Per Year', 'Per Year'), ('Per Month', 'Per Month'), ('Per week', 'Per week'), ('Per Day', 'Per Day'), ('Per Hour', 'Per Hour'), ('Per Project', 'Per Project')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Billing',
        ),
    ]
