# Generated by Django 4.2.7 on 2023-11-30 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_applying_experience_alter_jobs_pay_per_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='benifits',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='interview_type',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='is_urgent',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='tasks',
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_categories', to='main.category'),
        ),
    ]
