# Generated by Django 4.1.3 on 2022-12-20 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_privacy_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myjobs', to='main.category'),
        ),
    ]
