# Generated by Django 4.1.3 on 2022-12-25 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='salary_currency',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
