# Generated by Django 4.1.3 on 2022-12-25 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_jobs_salary_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='salary_currency',
            field=models.CharField(choices=[('€ Euro', '€ Euro '), ('$ USD', '$ USD'), ('£ EGP', '£ EGP')], max_length=15, null=True),
        ),
    ]
