# Generated by Django 4.1.3 on 2022-12-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_jobs_job_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Get_industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
