# Generated by Django 4.1.3 on 2022-12-20 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_get_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='main.shifts'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typeofjob', to='main.job_type'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='work_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workplace', to='main.work_from'),
        ),
    ]
