# Generated by Django 4.1.3 on 2022-12-26 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_jobs_salary_jobs_salary_from_jobs_salary_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applying',
            name='expected_salary_currency',
            field=models.CharField(choices=[('€ Euro', '€ Euro '), ('$ USD', '$ USD'), ('£ EGP', '£ EGP')], max_length=15, null=True),
        ),
    ]
