# Generated by Django 4.1.3 on 2022-12-27 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_applying_expected_salary_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applying',
            name='expected_salary_currency',
            field=models.CharField(blank=True, choices=[('€ Euro', '€ Euro '), ('$ USD', '$ USD'), ('£ EGP', '£ EGP')], max_length=15, null=True),
        ),
    ]
