# Generated by Django 4.1.3 on 2022-12-27 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_applying_expected_salary_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='num_people',
            field=models.CharField(blank=True, choices=[('1-10', '1-10'), ('11-20', '11-20'), ('21-49', '21-49'), ('50-99', '50-99'), ('100-249', '100-249'), ('250-499', '250-499'), ('500-999', '500-999'), ('1000 or more', '1000 or more')], max_length=25, null=True),
        ),
    ]
