# Generated by Django 4.1.3 on 2023-01-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_jobs_num_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchedJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_content', models.CharField(blank=True, max_length=500, null=True)),
                ('when', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
