# Generated by Django 4.1.3 on 2023-01-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_searchedjobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='number_user_facebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_l', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
