# Generated by Django 4.1.3 on 2022-12-19 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='subscription_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
