# Generated by Django 4.1.3 on 2023-01-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='selected_membership',
            field=models.CharField(choices=[('Free', 'Free'), ('Large enterprise', 'Large enterprise'), ('Mid-market enterprises', 'Mid-market enterprises'), ('Small business', 'Small business'), ('Trialing', 'Trialing')], max_length=150, null=True),
        ),
    ]
