# Generated by Django 4.1.3 on 2022-12-19 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_customer_subscription_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='subscription_id',
            new_name='track_id',
        ),
    ]
