# Generated by Django 4.1.3 on 2023-05-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True, max_length=100, null=True, unique=True)),
                ('facebook', models.URLField(blank=True, max_length=100, null=True, unique=True)),
                ('twitter', models.URLField(blank=True, max_length=100, null=True, unique=True)),
                ('github', models.URLField(blank=True, max_length=100, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('about', models.TextField()),
                ('zip_code', models.IntegerField(default=0)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company/%y/%m/%d')),
                ('profile_bg', models.ImageField(blank=True, null=True, upload_to='company/bg/%y/%m/%d')),
                ('founded', models.CharField(max_length=15)),
                ('co_size', models.CharField(choices=[('1-10', '1-10'), ('11-20', '11-20'), ('21-49', '21-49'), ('50-99', '50-99'), ('100-249', '100-249'), ('250-499', '250-499'), ('500-999', '500-999'), ('1000 or more', '1000 or more')], max_length=50)),
                ('industry', models.CharField(max_length=40)),
                ('company_name', models.CharField(max_length=30, unique=True)),
                ('is_profile_completed', models.BooleanField(default=False)),
                ('submition_date', models.DateTimeField(auto_now_add=True)),
                ('instagram', models.URLField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photos_c',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=500, null=True)),
                ('the_images', models.ImageField(upload_to='company/photos/%y/%m/%d')),
                ('is_public', models.BooleanField(default=True)),
                ('published_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
