# Generated by Django 4.1.3 on 2022-12-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='co_size',
            field=models.CharField(choices=[('1-10', '1-10'), ('11-20', '11-20'), ('21-49', '21-49'), ('50-99', '50-99'), ('100-249', '100-249'), ('250-499', '250-499'), ('500-999', '500-999'), ('1000 or more', '1000 or more')], max_length=50),
        ),
    ]
