# Generated by Django 4.1.3 on 2022-12-20 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applicants', '0008_alter_applicantprofile_city_and_more'),
        ('company', '0004_alter_companyprofile_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_city', to='applicants.cities'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_wilaya', to='applicants.wilaya'),
        ),
        migrations.AlterField(
            model_name='photos_c',
            name='photo_publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='photo_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
