# Generated by Django 4.1.3 on 2022-12-20 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0010_alter_applicantprofile_city_and_more'),
        ('company', '0005_alter_companyprofile_city_alter_companyprofile_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_city', to='applicants.cities'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_wilaya', to='applicants.wilaya'),
        ),
    ]
